name: Update My Projects Section

on:
  schedule:
    - cron: '0 2 * * *' # Runs daily at 2:00 UTC
  workflow_dispatch: # Allows manual runs from the Actions tab

jobs:
  update-projects:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Generate My Projects Section
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: python generate_projects_section.py

    - name: Commit and push changes
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "github-actions[bot]"
        git add my-projects.md
        git commit -m "chore: update my-projects.md [automated]" || echo "No changes to commit"
        git push